from time import sleep
from datetime import date
data = date.today().year
print(f'\033[1mInserir as notas Bismestrais de cada matéria em {data}\033[m')
sleep(0.5)
print('Primeiro Bimestre')
primeiro_b_m = float(input('Nota de Matemática:'.replace(',', '.')))
sleep(0.5)
primeiro_b_p = float(input('Nota de Português:'.replace(',', '.')))
sleep(0.5)
primeiro_b_q = float(input('Nota de Quimíca:'.replace(',', '.')))
sleep(0.5)
primeiro_b_f = float(input('Nota de Fisíca:'.replace(',', '.')))
sleep(0.5)
primeiro_b_b = float(input('Nota de Biologia:'.replace(',', '.')))
sleep(0.5)
primeiro_b_i = float(input('Nota de Inglês'.replace(',', '.')))
sleep(0.5)
primeiro_b_es = float(input('Nota de Espanhol:'.replace(',', '.')))
sleep(0.5)
primeiro_b_l = float(input('Nota de Literatura:'.replace(',', '.')))
sleep(0.5)
primeiro_b_ed = float(input('Nota de Ed. Fisíca:'.replace(',', '.')))
sleep(0.5)
primeiro_b_ar = float(input('Nota de Artes:'.replace(',', '.')))
print('\n', end='')
sleep(1)
print('Segundo Bimestre')
sleep(0.5)
segundo_b_m = float(input('Nota de Matemática:'.replace(',', '.')))
sleep(0.5)
segundo_b_p = float(input('Nota de Português:'.replace(',', '.')))
sleep(0.5)
segundo_b_q = float(input('Nota de Quimíca:'.replace(',', '.')))
sleep(0.5)
segundo_b_f = float(input('Nota de Fisíca:'.replace(',', '.')))
sleep(0.5)
segundo_b_b = float(input('Nota de Biologia'.replace(',', '.')))
sleep(0.5)
segundo_b_i = float(input('Nota de Inglês:'.replace(',', '.')))
sleep(0.5)
segundo_b_es = float(input('Nota de Espanhol:'.replace(',', '.')))
sleep(0.5)
segundo_b_l = float(input('Nota de Literatura:'.replace(',', '.')))
sleep(0.5)
segundo_b_ed = float(input('Nota de Ed. Fisíca:'.replace(',', '.')))
sleep(0.5)
segundo_b_ar = float(input('Nota de Artes:'.replace(',', '.')))
sleep(1)
print('Terceiro Bimestre')
sleep(0.5)
terceiro_b_m = float(input('Nota de Matemática:'.replace(',', '.')))
sleep(0.5)
terceiro_b_p = float(input('Nota de Português:'.replace(',', '.')))
sleep(0.5)
terceiro_b_q = float(input('Nota de Quimíca:'.replace(',', '.')))
sleep(0.5)
terceiro_b_f = float(input('Nota de Fisíca:'.replace(',', '.')))
sleep(0.5)
terceiro_b_b = float(input('Nota de Biologia:'.replace(',', '.')))
sleep(0.5)
terceiro_b_i = float(input('Nota de Inglês:'.replace(',', '.')))
sleep(0.5)
terceiro_b_es = float(input('Nota de Espanhol:'.replace(',', '.')))
sleep(0.5)
terceiro_b_l = float(input('Nota de Literatura:'.replace(',', '.')))
sleep(0.5)
terceiro_b_ed = float(input('Nota de Ed. Fisíca:'.replace(',', '.')))
sleep(0.5)
terceiro_b_ar = float(input('Nota de Artes:'))

sleep(1)
print('Quarto Bimestre')
sleep(0.5)
quarto_b_m = float(input('Nota de Matemática:'.replace(',', '.')))
sleep(0.5)
quarto_b_p = float(input('Nota de Português:'.replace(',', '.')))
sleep(0.5)
quarto_b_q = float(input('Nota de Quimíca:'.replace(',', '.')))
sleep(0.5)
quarto_b_f = float(input('Nota de Fisíca:'.replace(',', '.')))
sleep(0.5)
quarto_b_b = float(input('Nota de Biologia:'.replace(',', '.')))
sleep(0.5)
quarto_b_i = float(input('Nota de Inglês:'.replace(',', '.')))
sleep(0.5)
quarto_b_es = float(input('Nota de Espanhol:'.replace(',', '.')))
sleep(0.5)
quarto_b_l = float(input('Nota de Literatura:'.replace(',', '.')))
sleep(0.5)
quarto_b_ed = float(input('Nota de Ed. Fisíca:'.replace(',', '.')))
sleep(0.5)
quarto_b_ar = float(input('Nota de Artes:'.replace(',', '.')))
sleep(1)

soma_de_m = (primeiro_b_m + segundo_b_m + terceiro_b_m + quarto_b_m) / 4
soma_de_p = (primeiro_b_p + segundo_b_p + terceiro_b_p + quarto_b_p) / 4
soma_de_q = (primeiro_b_q + segundo_b_p + terceiro_b_p + quarto_b_p) / 4
soma_de_f = (primeiro_b_f + segundo_b_f + terceiro_b_f + quarto_b_f) / 4
soma_de_b = (primeiro_b_b + segundo_b_b + terceiro_b_b + quarto_b_b) / 4
soma_de_i = (primeiro_b_i + segundo_b_i + terceiro_b_i + quarto_b_i) / 4
soma_de_es = (primeiro_b_es + segundo_b_es + terceiro_b_es + quarto_b_es) / 4
soma_de_l = (primeiro_b_l + segundo_b_l + terceiro_b_l + quarto_b_l) / 4
soma_de_ed = (primeiro_b_ed + segundo_b_ed + terceiro_b_ed + quarto_b_ed) / 4
soma_de_ar = (primeiro_b_ar + segundo_b_ar + terceiro_b_ar + quarto_b_ar) / 4

if soma_de_ed and soma_de_ar and soma_de_l and soma_de_q and soma_de_p and\
        soma_de_i and soma_de_f and soma_de_m and soma_de_es >= 7:
    print(f'Aprovado\nParabéns!\nFeliz {data} e boas festas')
elif soma_de_m and soma_de_p and soma_de_q and soma_de_f and soma_de_b and soma_de_i and soma_de_es and\
        soma_de_l and soma_de_ed and soma_de_ar < 7:
    print(f'Reprovado!\nEstude mais e se esforce-se mais.\nFeliz {data} e boas festas')
